<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Matti Vuorre" />


<title>Importing data to R</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/sandstone.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; background-color: #dddddd; }
td.sourceCode { padding-left: 5px; }
code > span.kw { font-weight: bold; } /* Keyword */
code > span.dt { color: #800000; } /* DataType */
code > span.dv { color: #0000ff; } /* DecVal */
code > span.bn { color: #0000ff; } /* BaseN */
code > span.fl { color: #800080; } /* Float */
code > span.ch { color: #ff00ff; } /* Char */
code > span.st { color: #dd0000; } /* String */
code > span.co { color: #808080; font-style: italic; } /* Comment */
code > span.al { color: #00ff00; font-weight: bold; } /* Alert */
code > span.fu { color: #000080; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #ff0000; font-weight: bold; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #ff00ff; } /* SpecialChar */
code > span.vs { color: #dd0000; } /* VerbatimString */
code > span.ss { color: #dd0000; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { } /* Variable */
code > span.cf { } /* ControlFlow */
code > span.op { } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { font-weight: bold; } /* Preprocessor */
code > span.at { } /* Attribute */
code > span.do { color: #808080; font-style: italic; } /* Documentation */
code > span.an { color: #808080; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #808080; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #808080; font-weight: bold; font-style: italic; } /* Information */
div.sourceCode {
  overflow-x: visible;
}
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>

<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 61px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 66px;
  margin-top: -66px;
}

.section h2 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h3 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h4 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h5 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h6 {
  padding-top: 66px;
  margin-top: -66px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.9em;
  padding-left: 5px;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Toolbox 2.0</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="rrstudio.html">
    <span class="fa fa-code"></span>
     
    R &amp; RStudio
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-download"></span>
     
    Import
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="import.html">Spreadsheets</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-cogs"></span>
     
    Wrangle
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="reshape.html">Reshaping data</a>
    </li>
    <li>
      <a href="questionnaire.html">Questionnaire data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-area-chart"></span>
     
    Visualize
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="plotting.html">Intro to ggplot2</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/mvuorre/toolbox">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Importing data to R</h1>
<h4 class="author"><em>Matti Vuorre</em></h4>

</div>


<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>In SPSS or Excel, importing data is fairly self-explanatory: The user clicks through various menu items to locate the relevant data file in the computer’s hard drive, and opens the file. In R, the analoguous operation is to <em>read data to the environment</em> (the environment is just an abstract collection of objects that R has access to.) Here, we’ll locate data on the hard drive using RStudio’s file dialogue, import the file to the workspace, and print its content’s in the console. After learning how to work with a single source data file, we’ll cover how to import multiple source data files to R and combine them into a single object.</p>
</div>
<div id="single-source-data-file" class="section level1">
<h1>Single source data file</h1>
<p>This example data is a file downloaded from <a href="http://personality-testing.info/_rawdata/" class="uri">http://personality-testing.info/_rawdata/</a>, and contains answers to the <a href="http://personality-testing.info/tests/NPAS/">Nerdy Personality Attributes Scale</a>, along with some demographic variables. I have removed some variables from the file that are not relevant for the present purposes.</p>
<div id="locating-the-data-file" class="section level2">
<h2>Locating the data file</h2>
<p>If you have downloaded the toolbox materials, the relevant folder for this tutorial is <code>/toolbox/</code>. So, we can fire up RStudio and navigate to the folder using RStudio’s file navigator, and set it as the working directory by clicking More -&gt; Set as Working Directory in the <strong>Files</strong> panel of RStudio.</p>
<p>The data file is in <code>/toolbox/data/nerdy/</code> and is called <code>NPAS-data.csv</code>. To find it, recall where you placed the <code>/toolbox/</code> folder on your computer. The <code>.csv</code> extension means that the data are in a Comma Separated Values format, which is a common format for data; any Excel spreadsheet, for example, can be exported as a <code>.csv</code>, and both Excel and SPSS can open <code>.csv</code> files. There is also a <code>codebook.txt</code> file, detailing what the various variables in the <code>.csv</code> file mean.</p>
<p>It’s important to recognize that R only looks for external files in the current working directory. You can see the current working directory on top of the R console, or print it in the console by typing <code>getwd()</code> and pressing <code>return</code>.</p>
</div>
<div id="importing-the-data-file" class="section level2">
<h2>Importing the data file</h2>
<p>Now that we know the location and name of the data file, and the current working directory, we can ask R to read the <code>.csv</code> file from the <code>data/</code> folder by using the relative path to the file. To read files to the R environment, we need a function that does just that: <code>read.csv()</code>. Assuming that your working directory is the <code>/toolbox/</code> folder, the command is</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">d &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/nerdy/NPAS-data.csv&quot;</span>)</code></pre></div>
<p>The above function, <code>read.csv()</code> takes multiple arguments, but for the present purposes we only passed the location and name of the file to it, as a text string, and save the function call to <code>d</code>. <code>d</code> now contains the contents of the <code>.csv</code> in a format that R understands, namely, it is a <code>data.frame</code>.</p>
<p>Why did we write <code>read.csv(&quot;data/nerdy/NPAS-data.csv&quot;)</code> instead of <code>read.csv(data/nerdy/NPAS-data.csv)</code>? Enclosing a string of text into quotation marks in R means that you are referring to a <em>string</em> of text, which is appropriate in this case. If you leave out the quotation marks, R thinks that you are talking about an object, which is not found in the R environment.</p>
<p>As a result of executing <code>d &lt;- read.csv(&quot;data/nerdy/NPAS-data.csv&quot;)</code>, there is now an <em>object</em> in the R environment, called <code>d</code>:</p>
<p><img src="images/workspace.png" alt="workspace"></p>
</div>
<div id="show-me-the-data" class="section level2">
<h2>Show me the data</h2>
<p>Now that <code>d</code> is in the R environment, we can look at it in various ways. If you click on the little blue arrow next to <code>d</code> in the Environment pane, you’ll get a quick overview of what <code>d</code> contains:</p>
<p><img src="images/show-d.gif" alt="show-d"></p>
<p>First, you’ll see that there are 1418 observations (rows) and 4 variables (columns). Clicking the arrow reveals the names, types, and first 10 values of each of these columns. Clicking on <code>d</code> itself (in the Environment pane) opens up the data viewer, which is very useful for looking at the data in a format familiar from SPSS and Excel:</p>
<p><img src="images/viewer.png" alt="viewer"></p>
<p>This view reveals more of the actual values of the variables, and you can scroll up and down to inspect the entire <code>data.frame</code>.</p>
<p>Finally, we’ll view the data within the R console, by typing a few simple commands. There are two very useful functions to quickly look at the data: <code>str()</code> and <code>head()</code>. <code>str()</code> prints out the structure of the <code>data.frame</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(d)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    1445 obs. of  4 variables:
##  $ education: int  3 4 3 4 1 2 2 2 3 1 ...
##  $ age      : int  69 50 22 44 17 18 18 21 25 17 ...
##  $ major    : Factor w/ 404 levels &quot;&quot;,&quot; None yet&quot;,..: 395 79 70 288 1 220 1 1 363 1 ...
##  $ nerdy    : int  7 6 7 7 6 5 6 5 7 7 ...</code></pre>
<p>And <code>head()</code> shows the first six rows of the <code>data.frame</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(d)</code></pre></div>
<pre><code>##   education age       major nerdy
## 1         3  69  Studio Art     7
## 2         4  50  biophysics     6
## 3         3  22     biology     7
## 4         4  44 Mathematics     7
## 5         1  17                 6
## 6         2  18     Geology     5</code></pre>
<p>You could also print out the entire contents of the <code>data.frame</code>, but 1418 rows would result in an information overflow, so I won’t show the results of doing that. You can try it by typing <code>d</code> in the console, and hitting <code>return</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">d</code></pre></div>
<p><small><code>results not shown</code></small></p>
</div>
<div id="figure" class="section level2">
<h2>Figure</h2>
<p>Usually, the best way to investigate data is by looking at figures. I’ll draw one here, but won’t reveal the code quite yet, as plotting is covered in later tutorials. By following through the toolbox tutorials, you’ll be able to draw similar plots in no time!</p>
<div class="figure" style="text-align: center">
<img src="import_files/figure-html/unnamed-chunk-1-1.png" alt="Mean nerdiness (±1 SEM) for most common majors." width="768" />
<p class="caption">
Mean nerdiness (±1 SEM) for most common majors.
</p>
</div>
<p>Psychology, highlighted in red, sits comfortably in the middle. Of interest is also the fact that people who reported their major as “<em>math</em>” instead of <em>mathematics</em> reported lower nerdiness scores, although they have the same major.</p>
<p>Now that we’ve covered working with a single source data file, we’ll move on to multiple source data files.</p>
</div>
</div>
<div id="multiple-source-files" class="section level1">
<h1>Multiple source files</h1>
<p>In psychology, it is common to have multiple source data files that need to be combined for statistical analyses. For example, an experiment might produce a data file for each participant: In this case, the shape of the data is always the same (same variables collected on every participant, and possibly an equal amount of observations [rows]). Another example is a multi-site project, where, for example, multiple investigators collected personality questionnaires in various countries. Again, these files need to be combined for analyzing each country’s data together. I’ll use this latter case as an example.</p>
<p>In this example, we’ll learn to work with multiple source data files using the same data as in the <a href="questionnaire.html">questionnaire data project</a>. These data are responses to the Big Five personality questionnaire from over 100 countries, and are freely available <a href="http://personality-testing.info/_rawdata/">here</a> (open data wins again!).</p>
<div id="show-your-work" class="section level2">
<h2>Show your work</h2>
<p>In order to analyse all the data in R (or any other program), the files need to be combined into one object within the programming environment. Additionally, we can create a shortcut for later analyses by saving this “master” data object into a file. However, it is crucial that you don’t just save this new master file, but also the first step in the data analytic pipeline: The merging of multiple source files. After all, it is possible that we commit an error at this stage, and if we haven’t detailed what happened at this stage, we will not know what that error was, or how it influenced the data we analysed. Therefore, I strongly recommend saving the R script that produces master data frames from raw data. This constitutes the first note on the paper trail we leave for future investigators, including your future self. Now that we’re motivated to begin a reproducible workflow, let’s locate the files.</p>
</div>
<div id="locating-the-files" class="section level2">
<h2>Locating the files</h2>
<p>The raw data downloaded from the <a href="http://personality-testing.info/_rawdata/BIG5.zip">website</a> is a neat and simple spreadsheet, but for our purposes, I’ve split the data into separate files by country. To look at the source files, we use the <code>list.files()</code> function that simply takes a path as input, and shows what’s in that path. These data are located in <code>data/countries/</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">file_path &lt;-<span class="st"> &quot;data/big5/countries/&quot;</span>
<span class="kw">length</span>(<span class="kw">list.files</span>(file_path))  <span class="co"># How many files are there?</span>
<span class="kw">list.files</span>(file_path)[<span class="dv">1</span>:<span class="dv">5</span>]  <span class="co"># Show first 5 names</span></code></pre></div>
<pre><code>## [1] 155
## [1] &quot;AE.csv&quot; &quot;AG.csv&quot; &quot;AL.csv&quot; &quot;AO.csv&quot; &quot;AP.csv&quot;</code></pre>
<p>The <code>[1:5]</code> means that I would only like to access elements 1 through 10 of this object, i.e. the first ten names. We would certainly like to avoid manually copying and pasting these 155 files into one master file in Excel. Fortunately, programming allows us to <a href="https://en.wikipedia.org/wiki/Don&#39;t_repeat_yourself">DRY</a>, and we can load and merge these data with a few lines of code.</p>
<p>Before we begin, make sure that your working directory is set by running <code>getwd()</code>: It should be the <code>toolbox/</code> folder.</p>
</div>
<div id="merging-two-data-files" class="section level2">
<h2>Merging two data files</h2>
<p>The first step is to investigate what the shape of the data is, so let’s read and investigate a single source file, the Big Five questionnaire responses from Papua New Guinea.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pg &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/big5/countries/PG.csv&quot;</span>)
<span class="kw">str</span>(pg)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2 obs. of  57 variables:
##  $ race   : int  3 13
##  $ age    : int  30 47
##  $ engnat : int  1 2
##  $ gender : int  1 1
##  $ hand   : int  1 1
##  $ source : int  1 1
##  $ country: Factor w/ 1 level &quot;PG&quot;: 1 1
##  $ E1     : int  4 1
##  $ E2     : int  1 2
##  $ E3     : int  3 3
##  $ E4     : int  2 4
##  $ E5     : int  5 4
##  $ E6     : int  2 3
##  $ E7     : int  5 3
##  $ E8     : int  2 4
##  $ E9     : int  3 3
##  $ E10    : int  2 4
##  $ N1     : int  5 2
##  $ N2     : int  3 1
##  $ N3     : int  5 4
##  $ N4     : int  1 4
##  $ N5     : int  5 5
##  $ N6     : int  4 4
##  $ N7     : int  2 5
##  $ N8     : int  4 2
##  $ N9     : int  4 3
##  $ N10    : int  4 4
##  $ A1     : int  3 3
##  $ A2     : int  5 3
##  $ A3     : int  3 2
##  $ A4     : int  5 4
##  $ A5     : int  2 3
##  $ A6     : int  5 4
##  $ A7     : int  2 2
##  $ A8     : int  5 3
##  $ A9     : int  4 4
##  $ A10    : int  4 4
##  $ C1     : int  2 4
##  $ C2     : int  4 3
##  $ C3     : int  2 3
##  $ C4     : int  4 3
##  $ C5     : int  2 2
##  $ C6     : int  5 3
##  $ C7     : int  3 5
##  $ C8     : int  4 4
##  $ C9     : int  2 2
##  $ C10    : int  3 2
##  $ O1     : int  5 5
##  $ O2     : int  1 3
##  $ O3     : int  5 2
##  $ O4     : int  1 5
##  $ O5     : int  4 5
##  $ O6     : int  1 2
##  $ O7     : int  4 4
##  $ O8     : int  5 4
##  $ O9     : int  5 2
##  $ O10    : int  4 5</code></pre>
<p>To learn about what I called the <strong>shape</strong> of the data, we need to know its dimensions. These are listed on top of the displayed output, above. The object <code>pg</code> is a data frame with 2 rows and 57 columns. Each row is an observation, and each column is a variable. The easiest merging operation would be to add more rows to this data from a data frame that has the same columns, such as the data collected in Guatemala:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gt &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/big5/countries/GT.csv&quot;</span>)</code></pre></div>
<p>This data frame also has 57 columns, and both data sets are two-dimensional<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>. To merge these data sets, we simply need to bind them by row. But before we merge data frames, we need to be sure that the columns mean the same thing in both. One way to do this is to inspect the names of the columns, and make sure that they match up. The <code>names()</code> function returns the column names of the data frame, and we can compare the names of two data frames by comparing them with the logical <code>==</code> (equals) operator:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(pg) ==<span class="st"> </span><span class="kw">names</span>(gt)</code></pre></div>
<pre><code>##  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
## [15] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
## [29] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
## [43] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
## [57] TRUE</code></pre>
<p>The equality between each column name in <code>pg</code> and <code>gt</code> is <code>TRUE</code>. This is machine language for: “Stuff’s the same.” We can therefore proceed and bind the data frames by row. For this task, Rs built-in <code>rbind()</code> is the right tool:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pg_and_gt &lt;-<span class="st"> </span><span class="kw">rbind</span>(pg, gt)</code></pre></div>
<p>Job done! Although we were able to efficiently combine two source data files with this procedure, many projects, such as this one, can have hundreds of source data files, and we wouldn’t want to write out <code>read.csv(&quot;XX.csv&quot;)</code> for each of the files separately. Therefore we’ll <em>write a function</em> that reads an arbitrary number of data files into a single object!</p>
</div>
<div id="merging-more-than-two-data-files" class="section level2">
<h2>Merging more than two data files</h2>
<p>A common task, such as this one, has of course been solved many times over, and we shouldn’t be wasting our time reinventing the wheel. We therefore will use a <a href="https://gist.github.com/crsh/357458c41fd3d554fb24">function that another R user has already shared</a> on the excellent open-source programming platform <a href="https://github.com/">GitHub</a>.</p>
<div id="creating-a-function" class="section level3">
<h3>Creating a function</h3>
<p>What follows is based on <a href="https://gist.github.com/crsh/357458c41fd3d554fb24">this function</a>, but I’ve tweaked it a little bit. First, here is what the function looks like:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batch_read &lt;-<span class="st"> </span>function(path, extension) {
  file_names &lt;-<span class="st"> </span><span class="kw">list.files</span>(path, <span class="dt">pattern =</span> extension)
  data_list &lt;-<span class="st"> </span><span class="kw">lapply</span>(<span class="kw">paste0</span>(path, file_names), read.csv)
  data_frame &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(data_list)
  data_frame 
  }</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">batch_read  <span class="co"># Call a function without () to show the methods it contains</span></code></pre></div>
<pre><code>## function(path, extension) {
##   file_names &lt;- list.files(path, pattern = extension)
##   data_list &lt;- lapply(paste0(path, file_names), read.csv)
##   data_frame &lt;- bind_rows(data_list)
##   data_frame 
##   }</code></pre>
<p>Perhaps you can intuit that this function executes all the steps we already did above, but instead of merging two files, the function can merge a whole list of files! The printout above describes <code>batch_read()</code> as a <em>function</em> that takes two arguments: <code>path</code> and <code>extension</code>. When this function is executed, it first lists files in <code>path</code> whose filename include <code>extension</code>. This is extremely helpful, because the function now only reads files that have our pre-specified extension, and ignores all other file types. This list of file names is saved to <code>file_names</code>.</p>
<p>The second line is a little more complicated, but not much! (One reason it looks more complicated than it is has to do with <a href="questionnaire.html">nesting functions vs. piping functions</a>). The innermost function <code>paste0()</code> concatenates multiple text strings together, without spaces (hence <code>paste0</code> instead of <code>paste</code>):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">string1 &lt;-<span class="st"> &quot;Hello&quot;</span>
string2 &lt;-<span class="st"> &quot;world!&quot;</span>
<span class="kw">paste</span>(string1, string2)</code></pre></div>
<pre><code>## [1] &quot;Hello world!&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">paste0</span>(string1, string2)</code></pre></div>
<pre><code>## [1] &quot;Helloworld!&quot;</code></pre>
<p>Because <code>path</code> is a text string, and <code>file_names</code> is a list of text strings, the result is a new list of text strings. The result of <code>paste0(path, file_names)</code> is then passed to <code>lapply()</code>, which simply means <em>list apply</em>. <code>lapply()</code> takes as its first argument a list, here the list of file names. The second argument to <code>lapply()</code> is the function to apply to the list: We want to <code>read.csv()</code>. This line, therefore, <em>reads a list of csv files</em>, and saves the list into <code>data_list</code>: A list containing a whole bunch of data frames create by repeatedly applying <code>read.csv()</code> to file names in the list of names.</p>
<p>A final step remains: The list needs to be unpacked into a data frame. We simply passed the list of data frames (<code>data_list</code>) to <code>bind_rows()</code>, which then created a single object (called <code>data_frame</code>). The last line of the function definition specifies what is to be returned when a user calls this function.</p>
<p>I said before that programming is hard. You learn it by doing it. The preceding discussion is abstract and elusive and we will learn faster by implementing the function ourselves. To create this function, type the following code into your R script, and run it:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)  <span class="co"># We need this for the bind_rows() function</span>
batch_read &lt;-<span class="st"> </span>function(path, extension) {
  file_names &lt;-<span class="st"> </span><span class="kw">list.files</span>(path, <span class="dt">pattern =</span> extension)
  data_list &lt;-<span class="st"> </span><span class="kw">lapply</span>(<span class="kw">paste0</span>(path, file_names), read.csv)
  data_frame &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(data_list)
  data_frame
}</code></pre></div>
<p>If you now look at your Environment pane in RStudio, you’ll see <code>batch_read</code> under the <strong>Functions</strong> label. You can now call this function by typing in <code>batch_read(folder_where_revolutionary_data_lives, file_extension)</code>. Brilliant!</p>
</div>
<div id="read-multiple-files-with-batch_read" class="section level3">
<h3>Read multiple files with <code>batch_read()</code></h3>
<p>Let’s put our shiny new <code>batch_read()</code> to use and load our data. Recall that <code>file_path</code> is an object that simply contains, as a text string, the folder where the country-specific data files are: data/big5/countries/</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">d &lt;-<span class="st"> </span><span class="kw">batch_read</span>(file_path, <span class="st">&quot;.csv&quot;</span>)</code></pre></div>
<p>There! We read all the .csv files in <code>file_path</code> (data/big5/countries/). If we would like to save the new master data file as a single .csv, we could run the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">write_csv</span>(d, <span class="dt">path =</span> <span class="st">&quot;data/big5/master-data.csv&quot;</span>)</code></pre></div>
</div>
<div id="view-combined-data" class="section level3">
<h3>View combined data</h3>
<p><code>d</code> now contains all the Big Five questionnaire responses, from all the data files:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(d)</code></pre></div>
<pre><code>## [1] 19324    57</code></pre>
<p>19324 rows and 57 columns. That’s a lot of data. To get to work with these data, take a look at the <a href="questionnaire.html">questionnaire data tutorial</a>.</p>
</div>
</div>
</div>
<div id="bonus-round" class="section level1">
<h1>Bonus round</h1>
<p>This was a pretty boring, but important, project, so let’s do something fun at the end. The country names in <code>d</code> are two letter codes (<a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO 3166-1 alpha-2</a> codes, specifically):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(<span class="kw">unique</span>(d$country)[<span class="dv">1</span>:<span class="dv">20</span>], <span class="st">&quot;...&quot;</span>)  <span class="co"># Print first 20 ISO2 labels and an ellipsis</span></code></pre></div>
<pre><code>##  [1] &quot;AE&quot;  &quot;AG&quot;  &quot;AL&quot;  &quot;AO&quot;  &quot;AP&quot;  &quot;AR&quot;  &quot;AS&quot;  &quot;AT&quot;  &quot;AU&quot;  &quot;AZ&quot;  &quot;BA&quot; 
## [12] &quot;BB&quot;  &quot;BD&quot;  &quot;BE&quot;  &quot;BF&quot;  &quot;BG&quot;  &quot;BH&quot;  &quot;BM&quot;  &quot;BN&quot;  &quot;BO&quot;  &quot;...&quot;</code></pre>
<p>It would be very informative if we could convert them to actual country names. Well, <a href="https://www.youtube.com/watch?v=yhTerzNFLbo">there’s an R package for that</a>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(countrycode)                                    <span class="co"># Install if necessary</span>
d$country &lt;-<span class="st"> </span><span class="kw">countrycode</span>(<span class="dt">sourcevar =</span> d$country,         <span class="co"># Source variable</span>
                         <span class="dt">origin =</span> <span class="st">&quot;iso2c&quot;</span>,              <span class="co"># Coding scheme</span>
                         <span class="dt">destination =</span> <span class="st">&quot;country.name&quot;</span>)  <span class="co"># I want their names!</span>
<span class="kw">c</span>(<span class="kw">unique</span>(d$country)[<span class="dv">1</span>:<span class="dv">20</span>], <span class="st">&quot;...&quot;</span>)  <span class="co"># Print again</span></code></pre></div>
<pre><code>##  [1] &quot;United Arab Emirates&quot;            &quot;Antigua and Barbuda&quot;            
##  [3] &quot;Albania&quot;                         &quot;Angola&quot;                         
##  [5] NA                                &quot;Argentina&quot;                      
##  [7] &quot;American Samoa&quot;                  &quot;Austria&quot;                        
##  [9] &quot;Australia&quot;                       &quot;Azerbaijan&quot;                     
## [11] &quot;Bosnia and Herzegovina&quot;          &quot;Barbados&quot;                       
## [13] &quot;Bangladesh&quot;                      &quot;Belgium&quot;                        
## [15] &quot;Burkina Faso&quot;                    &quot;Bulgaria&quot;                       
## [17] &quot;Bahrain&quot;                         &quot;Bermuda&quot;                        
## [19] &quot;Brunei Darussalam&quot;               &quot;Bolivia, Plurinational State of&quot;
## [21] &quot;...&quot;</code></pre>
<p>And finally, we’ll print out some arbitrary plot, and you should try to figure out what the code here does. If you are unsure about all the <code>mutate()</code>s etc. please refer back to the <a href="questionnaire.html">questionnaire data project</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(d, !<span class="kw">is.na</span>(country)) %&gt;%
<span class="st">    </span><span class="kw">group_by</span>(country) %&gt;%
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">N =</span> <span class="kw">n</span>()) %&gt;%
<span class="st">    </span><span class="kw">ungroup</span>() %&gt;%
<span class="st">    </span><span class="kw">filter</span>(N &gt;<span class="st"> </span><span class="dv">100</span>) %&gt;%
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">country =</span> <span class="kw">reorder</span>(country, N)) %&gt;%
<span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> N, <span class="dt">y =</span> country)) +
<span class="st">    </span><span class="kw">geom_point</span>()</code></pre></div>
<div class="figure" style="text-align: center">
<img src="import_files/figure-html/unnamed-chunk-16-1.png" alt="TRUE" width="768" />
<p class="caption">
TRUE
</p>
</div>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<p>Great info here: <a href="http://r4ds.had.co.nz/import.html" class="uri">http://r4ds.had.co.nz/import.html</a></p>
<div id="refs" class="references">

</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Two-dimensional data simply means that it has rows and columns. One-dimensional data would be a vector: A simple sequence of values. By and large, we deal with two-dimensional data (such as you see when you stare at an Excel spreadsheet), but data can take any number of dimensions. Think about what three-dimensional data would look like.<a href="#fnref1">↩</a></p></li>
</ol>
</div>

<!DOCTYPE HTML>
<!--custom footer for all pages-->
<!--centered text class-->
<style type="text/css">
.center {
    margin: auto;
    text-align: center;
    width: 60%;
    padding: 10px;
}
</style>
<hr>
<p class="center">
<a href="https://zenodo.org/badge/latestdoi/20002/mvuorre/toolbox"><img src="https://zenodo.org/badge/20002/mvuorre/toolbox.svg" alt="DOI"></a>
</p>
<br>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
